// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3B1ASKVFNO1n-h3-eadNaiDLUJZFVnEw',
    appId: '1:73599976793:web:8d291813f3e1fd856c7848',
    messagingSenderId: '73599976793',
    projectId: 'webkultask',
    authDomain: 'webkultask.firebaseapp.com',
    storageBucket: 'webkultask.appspot.com',
    measurementId: 'G-C1GNFX6BS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgz_62scxPmJJVWnPd6dUaxCaL686HtY',
    appId: '1:73599976793:android:e1a707509d19b1336c7848',
    messagingSenderId: '73599976793',
    projectId: 'webkultask',
    storageBucket: 'webkultask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqD5d5BqjIkbjHNziT9E9wQMmmUz009nM',
    appId: '1:73599976793:ios:2ebb40f70da6b6856c7848',
    messagingSenderId: '73599976793',
    projectId: 'webkultask',
    storageBucket: 'webkultask.appspot.com',
    iosClientId: '73599976793-ok6ir16t1m8gspkev2cloi0986n185qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.webkulTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqD5d5BqjIkbjHNziT9E9wQMmmUz009nM',
    appId: '1:73599976793:ios:af83db9c605d43236c7848',
    messagingSenderId: '73599976793',
    projectId: 'webkultask',
    storageBucket: 'webkultask.appspot.com',
    iosClientId: '73599976793-c15gts1vjee56iuvdh6m7sh77g9kj1i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.webkulTask.RunnerTests',
  );
}
